### ISSUE TITLE
Missing Abiltiy Template

### ISSUE THREAD

**Issue by Jmiles0099** [boundir/AdditionalActionPointAbility#1]
Hello boundir, I will get right to the point here. I can't seem to figure out if the mod is having any effect in my game play. The mod loads in the mod selection screen, and there is evidence that the mod is in effect.
![X2NameTemplate](https://user-images.githubusercontent.com/54779360/74305023-b3e12d00-4d2c-11ea-9f65-8378bd3cb532.PNG)

Do note that custom abilities I have made with the re purpose abilities mod, and the birthday ability in the immunities mod, all function properly in game.

 The mod does not seem to grant an extra ability point, even when it is referenced within the XComRepurposeAbilities.ini from the re purpose abilities mod.
![abilities](https://user-images.githubusercontent.com/54779360/74304784-03732900-4d2c-11ea-8468-d9e2ce40b5b3.PNG)

I do not know if it is an issue caused by mod conflicts, or if it does work, and I am just not recognizing it. Do let me know your thoughts, and in the mean time I will test things further. I have re-installed this twice, to seemingly no effect, but I may also try that again. Thank you for your time, and I truly appreciate what you have made for me, regardless of what the end result is.

**Comment by boundir** [comment]
Oops I didn't receive any notification. So if I understand correctly you put the ability in PlatedVest but didn't get the 3rd action?
The additional AP ability is called InitialAP in my files. That might be the reason you don't have it.

Also I know I'm the one who used this method in my examples but you will probably prefer using this notation instead:
```
+Abilities=(TemplateName=PlatedVest, AddAbilityName=(BirthdaySixteen, BirthdayTwenty, BirthdayThree, Birthday, InitialAP))
```

On a side note I think I will need to look back at my Create Abilities mods. I don't like the fact their description is not visible.

**Comment by boundir** [comment]
Also @Jmiles0099, did you remove all abilities from the Andromedon? 😅

**Comment by Jmiles0099** [comment]
I will test this out and let you know my results, and thanks for letting me know about the Andromedon mistake lol

**Comment by Jmiles0099** [comment]
The ability works, I was using the wrong ability name in the re purpose abilities ini file, I still see the missing name x2 ability template, but I assume that is some other issue. Thank you for giving me the correct ability name!
